name: Pruebas Automatizadas

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Dar permisos de ejecución a mvnw
        run: chmod +x ./mvnw
      
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Ejecutar pruebas
        run: ./mvnw test